### ISSUE TITLE
Run `dje::dje_to_text()` in parallel

### ISSUE THREAD

**Issue by jtrecenti** [courtsbr/dje#1]
Also remove annoying warning messagens when pdf to text fails.

![rstudio todosdje](https://user-images.githubusercontent.com/1425970/39485893-a6fa0ffe-4d50-11e8-8b8f-45f1cf4257a0.png)

**Comment by ctlente** [comment]
Fixed in 6d0753682886941337b2cc6f94c79b90f9f564b0. Will add progress once `abjutils::pvec()` is mature.
